# ===================================
#  Form Behavior Config
# ===================================

name: rainlab.blog::lang.blog.create_category
form: ~/plugins/digitalronin/wiki/models/category/fields.yaml
modelClass: RainLab\Blog\Models\Category
defaultRedirect: digitalronin/wiki/categories

create:
    redirect: digitalronin/wiki/categories/update/:id
    redirectClose: digitalronin/wiki/categories

update:
    redirect: digitalronin/wiki/categories
    redirectClose: digitalronin/wiki/categories
